- name: ansible copy file from remote to local.
  fetch:
    src: /home/administrator/.kube/config
    dest: "{{ playbook_dir }}/kubeconfig"
    flat: true
  when: ansible_hostname == groups[master_group][0]
