---
ansible_user: root
server_init_args: >-
  {% if (groups[master_group] | length) > 1 %}
    {% if inventory_hostname == (groups[master_group][0]) %}
      --cluster-init
    {% else %}
      --server https://{{ hostvars[groups[master_group][0]].k3s_node_ip }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %}
  {{ extra_server_args | default('') }}